### ISSUE TITLE
Save installation directory in travis build cache

### ISSUE THREAD

**Issue by sstaehler** [nemequ/icc-travis#11]
Is it possible to store the icc installation directory in the Travis cache to avoid reinstallation? My hope was to save some time during booting and avoid unnecessary traffic at the Intel servers ;)

I tried it the naive way, by adding $HOME/intel to the list of cached directories
(https://github.com/sstaehler/fortran_travis/blob/f1645287c10ce3b61012b79ffab7256794b9dab5/.travis.yml)
but it runs into a License error when using ifort
```
Error: A license for Comp-FL is not available (-9,57).
License file(s) used were (in this order):
    1.  Trusted Storage
**  2.  /home/travis/intel/compilers_and_libraries_2016.3.210/linux/licenses
**  3.  /opt/intel/licenses
**  4.  /home/travis/intel/licenses/l_K9CGNS7T.lic
**  5.  /home/travis/intel/compilers_and_libraries_2016.3.210/linux/bin/intel64/../../Licenses
**  6.  /home/travis/Licenses
**  7.  /Users/Shared/Library/Application Support/Intel/Licenses
**  8.  /home/travis/intel/compilers_and_libraries_2016.3.210/linux/bin/intel64/*.lic
Please visit http://software.intel.com/sites/support/ if you require technical assistance.
ifort: error #10052: could not checkout FLEXlm license
```

Did anyone of you ever test this (or is it a bad idea altogether)?

**Comment by ickc** [comment]
Is it because the license is associated with the machine, so booting from another virtual machine instance causes error?

**Comment by nemequ** [comment]
Yeah, I think the license is machine-dependent, so I don't think this will work.

That said, I seem to remember reading we shouldn't do this… Ah, here: https://docs.travis-ci.com/user/caching/#Things-not-to-cache

Maybe things have changed (i.e., perhaps Intel has made ICC uncacheable), but when I was developing this script I noticed that Travis *was* caching the download (they seem to be pretty good about caching HTTP requests, they probably run everything through a proxy).  If you run multiple builds in relatively quick succession the first build will be **much** slower.  Basically, this seems to be the sort of thing Travis doesn't want in the build cache.

I'm going to go ahead and close this, but If I've misunderstood something (or if someone from Travis requests), I'd be happy to reopen it.
