### ISSUE TITLE
Any chance it might work in a docker image?

### ISSUE THREAD

**Issue by Jellby** [nemequ/icc-travis#12]
I tried to install it (icc,ifort) in a docker image. It seemed to work (I had to install cpio first, which apparently wasn't checked by the intel script), but when I then I try using the image elsewhere I get:

```
$ ifort
FNPLicensingService[28]: FNPLicensingService: Unable to run service (No such file or directory), Location = /usr/local/share/FNP/service64/11.13.0/FNPLicensingService

Error: A license for Comp-FL is not available (-157,424).

License file(s) used were (in this order):
    1.  Trusted Storage
**  2.  /root/intel/compilers_and_libraries_2016.3.210/linux/licenses
**  3.  /opt/intel/licenses/*.lic
**  4.  /root/intel/licenses
**  5.  /root/intel/compilers_and_libraries_2016.3.210/linux/bin/intel64/../../Licenses
**  6.  /root/Licenses
**  7.  /Users/Shared/Library/Application Support/Intel/Licenses
**  8.  /root/intel/compilers_and_libraries_2016.3.210/linux/bin/intel64/*.lic

Please visit http://software.intel.com/sites/support/ if you require technical assistance.

ifort: error #10052: could not checkout FLEXlm license
```

Just running ``ifort`` on the same session after installing it gives the first line, but otherwise it compiles a working executable. So this may be related to machine identification. Or it could be that I'm using a trial license (I know it's not the best option). Would it be possible to use this image with the installed compilers and just "activate" it before running any job?

**Comment by nemequ** [comment]
This is something you'd have to take up with Intel, but it seems like the license manager is doing exactly what it's designed to do, which is to prevent people from running icc/ifort on platforms it's not licensed for.

> Would it be possible to use this image with the installed compilers and just "activate" it before running any job?

I'm not aware of a way to do that, and I don't see anything obvious in my local installation, but again you'll have to [ask Intel](https://software.intel.com/en-us/forums/intel-software-development-products-download-registration-licensing).
