### ISSUE TITLE
"realpath" is not reliable

### ISSUE THREAD

**Issue by Jellby** [nemequ/icc-travis#13]
The script uses `realpath` to parse the destination directory, but at least in Ubuntu 14.04 (which is one of the "supported OS" of icc 2016) `realpath` returns failure if the directory does not exist. The desired functionality can be obtained with `readlink -m`, but that will probably not work in other OS... Maybe just use `mkdir -p` directly, since it doesn't fail if the directory exists?

**Comment by jeffhammond** [comment]
Can you point to a Travis log that shows this failing?

**Comment by Jellby** [comment]
No, sorry, I was just testing it "live" on an Ubuntu 14.04 installation, but the output is:

```
./install-icc.sh: 51: ./install-icc.sh: realpath: not found
 does not exist, creating...
mkdir: cannot create directory '': No such file or directory
mkdir: cannot create directory '': No such file or directory
```

Downloading continued and then:

```
Fatal error: silent install config is not valid.
Installation attempt #1 completed, but unable to find compilervars.sh.
find: cannot search `': No such file or directory
```

And this is all because (if `foo` does not exist):

```
$ realpath foo ; echo $?
foo: No such file or directory
1
```

while:

```
$ readlink -f foo ; echo $?
/home/user/foo
0
```

So I fixed it with:

```
wget -q -O /dev/stdout 'https://raw.githubusercontent.com/nemequ/icc-travis/master/install-icc.sh' | sed 's/realpath/readlink -m/' | /bin/sh -s -- --components icc,ifort
```

**Comment by jeffhammond** [comment]
I guess I don't understand why this needs to be fixed, since it works just fine in Travis CI already, but you are welcome to submit a pull request with the changes you want.

The script here is mostly a wrapper around the existing non-interactive (i.e. silent) install Intel Parallel Studio.  You might find that it is easier to just use that for your local installs.

**Comment by Jellby** [comment]
SInce I don't use Travis CI, I can't say if it works or not... I was testing it locally, but my goal is using it on GitLab CI. What I found is that the `relpath` line works in Ubuntu 16.04, but not in 14.04. Is there some Travis CI installation that uses Ubuntu 14.04 and works with this script?

And I don't say it needs to be fixed, just pointing out a compatibility issue.

**Comment by jeffhammond** [comment]
Travis runs Ubuntu 14.04 (and 12.04?) and this script works there. 

In any case, if/when you submit a pull request, this repo will test the changes in Travis. It would be pretty silly for this repo to not support Travis testing :-D

**Comment by nemequ** [comment]
`readlink -f` isn't really any better.  According to the man page, "all but the last component must exist".

Maybe something like (untested):

```bash
if [ ! -e "$DIR" ]; then
  mkdir -p "$DIR" || exit 1
fi
DIR="`realpath "$DIR"`"
```

?

**Comment by jeffhammond** [comment]
AFAIK "mkdir -p ${DIR}" can be used unconditionally.

**Comment by nemequ** [comment]
If it doesn't return an error code if the target already exists that's fine with me (can't try it right now, typing on phone).  Just want to make sure we error on stuff like EPERM.

**Comment by jeffhammond** [comment]
https://stackoverflow.com/questions/16633066/bash-how-to-test-for-failure-of-mkdir-command/16633129#16633129 confirms my recollection that -p suppresses failure on prior existence.

**Comment by nemequ** [comment]
Closing since this issue is obsolete now that the APT repository works.
