### ISSUE TITLE
compilervars.sh executed, not sourced

### ISSUE THREAD

**Issue by ikirker** [nemequ/icc-travis#2]
At: 
  https://github.com/nemequ/icc-travis/blob/master/install-icc.sh#L186

You've got this line in the wrapper script: 
```bash
/bin/bash "${DESTINATION}"/compilers_and_libraries_2016/linux/bin/compilervars.sh intel64
```

I wasn't sure if you've done this for a reason, but since this script sets up a bunch of variables, by my reading this should instead be:
```bash
source "${DESTINATION}"/compilers_and_libraries_2016/linux/bin/compilervars.sh intel64
```
(Or you could just use `.` but `source` is less missable IMO.)

FWIW, on our cluster, we use this Tcl environment module to set the variables ourselves: https://github.com/UCL-RITS/rcps-modulefiles/blob/master/compilers/compilers/intel/2015/update2

**Comment by ikirker** [comment]
(I'd fork and test this, but we have a license server rather than a serial number and I haven't worked out how to get through the firewall without causing problems yet.)

**Comment by nemequ** [comment]
IIRC I did do that for a reason, but it was just an experiment; you're right that it should be sourced, so I've pushed a fix.  [It doesn't really make a difference, though](https://travis-ci.org/nemequ/icc-travis/builds/90129232).  The libraries simply aren't installed (`find $DESTINATION -name 'libimf.so*'`comes up empty).

As for forking, AFAIK you could fork this then use a PR to have Travis build it using my SN.  Once you want to build your own projects, though, you would need to get hold of a serial number (or, with a bit of work, the script could be made to work with a license file).
