### ISSUE TITLE
"Maximum number of activations exceeded."

### ISSUE THREAD

**Issue by lawinslow** [nemequ/icc-travis#3]
@nemequ Any experience dealing with the activation limit for the intel compiler? I was using an open-source community license and started getting "Maximum number of activations exceeded." while trying to experiment using your example. I'm worried getting this working for my build may hit a license wall regardless of the technological solution. 

Thanks!

**Comment by nemequ** [comment]
Sorry, I didn't see anything like that when I was submitting lots of changes pretty quickly.  Maybe it's new?  I would try asking on [Intel's "Intel® Software Development Products Download, Registration & Licensing" forum](https://software.intel.com/en-us/forums/intel-software-development-products-download-registration-licensing).

**Comment by nemequ** [comment]
You might be able to get around it by using a license file instead of the serial number.  Search for "ACTIVATION_LICENSE_FILE" in https://software.intel.com/en-us/articles/intel-composer-xe-2015-silent-installation-guide

**Comment by lawinslow** [comment]
Yeah, good point on the license file. I'll need to figure out if that's something I can just stick it up on a repo or if it needs to be securely stored.

**Comment by nemequ** [comment]
I'm pretty sure it needs to be securely stored.  [Travis supports encrypted file](https://docs.travis-ci.com/user/encrypting-files/), so the only real issue should be figuring how to get one from Intel and documenting everything.

**Comment by lawinslow** [comment]
I may have a surprisingly simple solution. I think the license files are linked to machine mac address (at least for some license types) but `ACTIVATION_TYPE=trial_lic` seems to be working thus far.

**Comment by sunoru** [comment]
I got an error like this when using trial_lic to install icc : 

> Sorry, but the Trial License Activation does not work in silent mode on this environment. If you still want to use it, please run installation in usual mode.

So it seems to be unable to use trial_lic in travis CI?

**Comment by nemequ** [comment]
I've saw that error, too.  Using a real license seems fine, and I haven't had any problem with the maximum number of activations being exceeded.  That will probably only be an issue for *very* active projects…

**Comment by lawinslow** [comment]
Just checked again, trial license worked fine here
https://travis-ci.org/GLEON/GLM-source/builds/115211341

Might be a config difference?

**Comment by nemequ** [comment]
Maybe… we're both using trusty with sudo, so I'm not sure why there would be a difference…  https://github.com/quixdb/squash/blob/master/.travis.yml FWIW.

**Comment by sunoru** [comment]
I just used the install-icc.sh in GLEON/GLM-source of @lawinslow and add sudo and trusty in my .travis.yml

and it seemed to work

**Comment by sunoru** [comment]
And then I got `Installer checksum verification failed` again and again.. Maybe a network problem?..

**Comment by nemequ** [comment]
IIRC I've seen that error on rare occasions, but not repeatedly.  Now that it's been a few hours, maybe you could try just re-running the job?

**Comment by sunoru** [comment]
Yeah it works now

**Comment by rakhimov** [comment]
The same issue is here https://travis-ci.org/rakhimov/scram/jobs/149136422
I probably installed around 5 times before getting it work withing 2 hours.
This approach is going to be very limiting for active projects.

It looks like that the license files are specific/unique to an installation machine,
so it is not flexible with servers as well.

**Comment by nemequ** [comment]
> The same issue is here https://travis-ci.org/rakhimov/scram/jobs/149136422
> I probably installed around 5 times before getting it work withing 2 hours.
> This approach is going to be very limiting for active projects.

I've done *many* more than that while working on this script (probably 5 times in 20 minutes), and I haven't encountered this issue.

I just found https://software.intel.com/en-us/articles/what-to-do-when-you-see-the-message-maximum-number-of-activations-exceeded which may be helpful.  It also mentions uninstalling, so if we can figure out how to use that perhaps we could add an optional uninstall step

**Comment by rakhimov** [comment]
@nemequ I emailed them. Let you know when I get response.

**Comment by nemequ** [comment]
In the meantime, can you try adding something like

```yaml
after_script:
- find ${HOME}/intel -name uninstall.sh -exec {} \;
```

To your .travis.yml (assuming you installed to the default location)?  Or maybe just

```yaml
after_script:
- ${HOME}/intel/parallel_studio*/uninstall.sh
```

**Comment by nemequ** [comment]
Actually, I just remembered that the CI for this project is run in 8 configurations, so we install 8 copies in just a couple minutes.

We now have a special license so we can check to make sure MPI works, but until quite recently it was just using a key I got through the open source contributor program, and this was never an issue for me with either this project or Squash (which makes this really hard to debug).

**Comment by rakhimov** [comment]
Still failing: https://travis-ci.org/rakhimov/scram/jobs/149239552

**Comment by nemequ** [comment]
That makes sense, it can't uninstall the copies installed in old (discarded) containers/VMs.  Also, the uninstall step doesn't occur until after the install fails, and the wildcard doesn't seem to work in Travis' yaml (see the error at the end).

My hope is that if you cleanly uninstall copies which were successfully installed instead of simply discarding them your available number of activations will go back up.  Basically, for this to be effective you would have to wait until you are able to activate new installs again, and hopefully the issue won't reappear.

**Comment by rakhimov** [comment]
By the way,
this failure doesn't cause the script to return 1 and make Travis run "error" instead of "fail".
My build is failing upon calling "compilervars.sh" not found.
Should this be a separate issue?

**Comment by rakhimov** [comment]
@nemequ My CI licenses have been released and now it works on Travis. However, the uninstall script is interactive, the silent mode requiring a configuration file.

**Comment by rakhimov** [comment]
The ``uninstall.sh --silent`` seems to be working. I will let you know if hit the maximum number again.

**Comment by nemequ** [comment]
> My build is failing upon calling "compilervars.sh" not found.
> Should this be a separate issue?

Hrm, I think that is really an issue for Intel.  Looking at the code, we have

```bash
("${INSTALLER}" \
    -t "${TEMPORARY_FILES}" \
    -s "${SILENT_CFG}" \
    --cli-mode \
    --user-mode && \
touch "${SUCCESS_INDICATOR}") &

# ...

if [ ! -e "${SUCCESS_INDICATOR}" ]; then
    echo "Installation failed."
    exit 1
fi
```

So if the file is touched the blame lies with Intel.  If the script exits with an error code but Travis keeps going there isn't anything we can do.  For now I've (hopefully) worked around it with:

```bash
if [ ! -e "${SUCCESS_INDICATOR}" -o ! -e "${DESTINATION}/bin/compilervars.sh" ]; then
    echo "Installation failed."
    exit 1
fi
```

> However, the uninstall script is interactive, the silent mode requiring a configuration file.

The uninstall scripts work with -s, except for ism ("Intel Software Manager"?), but we don't really need to worry about ism.  I've added a quick `uninstall_intel_software` function to ~/.bashrc which uninstalls everything *except* ism, so adding

```yaml
after_script:
  - '[[ ! -z "${INTEL_INSTALL_PATH}" ]] && uninstall_intel_software'
```

Should work.  I'm going to close this, since I think that's really all we can do.

**Comment by rakhimov** [comment]
I happened again: https://travis-ci.org/rakhimov/scram/jobs/149885387
uninstall doesn't help.

**Comment by nemequ** [comment]
Uninstall wouldn't help there; that has nothing to do with the number of activations being exceeded.

In order to get around the issue you mentioned where the installer returns success but nothing is actually installed (i.e., there is no `bin/compilervars.sh`), I tried to add a loop to remove the install data and retry.  Unfortunately, I removed the downloader script as well.  Hopefully 1a7d14dff61bba4ad651c41324d11279a2852e63 fixes it.

**Comment by rakhimov** [comment]
This is the response I got from bothering Intel folks:

>How many VMs are you installing on?  The license allows up to 5 activations (EULA states 3).  You can release the activations yourself by logging into the Intel Registration Center, selecting your product, and clicking the "Manage" link next to the license.  There you will see the host IDs for your activations, and clicking the X on the right will release them.  But it seems like the script you're running will continue to hit this error when it hits the 6th activation.

**Comment by nemequ** [comment]
Are you running on more than 5 VMs at once?  I'd think you would only test ICC in only one or two configurations at a time, but Travis' free option usually limits you anyways (I usually see between 2 and 5 parallel builds).  You could always [limit the number of concurrent builds](https://docs.travis-ci.com/user/customizing-the-build/#Limiting-Concurrent-Builds), too.  Assuming uninstalling frees up a host, that shouldn't be a problem.

It really seems like the problem with maximum number of activaitons being exceeded should be resolved by uninstallation.  AFAICT the only problem you may still see is the issue where Intel's installer silently just doesn't install anything (yet returns successfully) which, as I mentioned, should be resolved by 1a7d14dff61bba4ad651c41324d11279a2852e63.

**Comment by rakhimov** [comment]
>Are you running on more than 5 VMs at once?
No, it's only one icc. https://travis-ci.org/rakhimov/scram/builds/149885380

I don't think the uninstall is helping release the activation.
I am running one job and tracking my registration center to see if it works.
Upon releasing activations myself, I was asked to confirm that I uninstalled the software and removed activation files.

**Comment by rakhimov** [comment]
I wonder if Travis VM eth0 addresses are random,
and it is very unlikely to run out of trial versions.
This would be an abuse ,though.

**Comment by rakhimov** [comment]
Some additional info from Intel:
>... At this time I don't know of any way to automatically release the activation.  Even the ability for customers to release activations is very new and we haven't updated the documentation yet, but it's something we're working on.

**Comment by nemequ** [comment]
The behavior @rakhimov described is happening to me now (since my old license expired and I got a new one).  We can't really do much about this unless Intel provides a way to automatically unregister an installation (preferably via the `uninstall.sh` script they distribute), but we can use this issue to track Intel's response.

As far as I'm concerned this issue pretty much cripples this script.  @jeffhammond, perhaps there is someone you can poke about it?

**Comment by jeffhammond** [comment]
@nemequ I don't see this issue.  I'm not sure why.  You might have better luck generating the license file itself offline and using that instead of the license number.  If you use a license file, the installation shouldn't need to phone home.

**Comment by rakhimov** [comment]
@jeffhammond I believe the license is tied to the machine, and Travis has VMs that couldn't be assigned persistently to the account. I think without Intel's initiative we are helpless right now.

**Comment by jeffhammond** [comment]
> @jeffhammond <https://github.com/jeffhammond> I believe the license is
> tied to the machine, and Travis has VMs that couldn't be assigned
> persistently to the account.
>
 Can please try it? That's not my experience.


-- 
Jeff Hammond
jeff.science@gmail.com
http://jeffhammond.github.io/

**Comment by rakhimov** [comment]
@jeffhammond Upon an attempt to generate a license and download it from the Intel registration center, it asks me ``host id``, which I don't have for Travis machines.
I believe you have a license that is not ``system locked``,
which is not what Intel provides for open-source folks by default.

**Comment by jeffhammond** [comment]
> @jeffhammond Upon an attempt to generate a license and download it from the Intel registration center, it asks me host id, which I don't have for Travis machines.
> I believe you have a license that is not system locked,
> which is not what Intel provides for open-source folks by default.
> 
Ah ok I guess that makes sense. I have an employee license, which I guess is an unlimited commercial one. 

I'll try to figure this out for you.

**Comment by nemequ** [comment]
Closing since this issue is obsolete now that the APT repository works.  See the README for directions.
