### ISSUE TITLE
Issue linking intel libraries

### ISSUE THREAD

**Issue by lawinslow** [nemequ/icc-travis#4]
Hi @nemequ, I've been trying to solve this issue.

> $ icc -o test/test test/test.c
> /home/travis/.local/bin/icc: 3: /home/travis/.local/bin/icc: source: not found
> ld: cannot find -limf
> ld: cannot find -lsvml
> ld: cannot find -lirng
> ld: cannot find -lipgo
> ld: cannot find -ldecimal
> ld: cannot find -lirc
> ld: cannot find -lsvml

I've found those libraries available as part of the [intel redistributable libraries](https://software.intel.com/en-us/articles/redistributables-for-intel-parallel-studio-xe-2016-composer-edition-for-linux). Any clue as to if that needs to be installed as well? Installing seems to make them available, though I don't know how to properly link them into the build environment (manual fiddling with LD_LIBRARY_PATH?)

**Comment by nemequ** [comment]
That's where I stopped; it's actually the error linked to in the first paragraph of the README.

If you install ICC through the regular (non-silent) installer it works, so I'm pretty sure it is just a matter figuring out which components are required and adjusting the `COMPONENTS_*` variables at the beginning of the script to reflect those needs.

As for making sure the system picks them up, I think that sourcing `compilervars.sh` (see line  should prepare the environment.  AFAICT that is the "official" way of doing it, and that is what the wrapper scripts we dump into ~/.local/bin do.

**Comment by lawinslow** [comment]
Yeah, I just wanted to make an issue for discussion.

**Comment by nemequ** [comment]
Okay, got it working with destinations other than /opt/intel.  The main trick was to use bash instead of dash for the wrapper scripts, so that sourcing compilervars.sh works properly.
