### ISSUE TITLE
"Sorry, but the Trial License Activation does not work in silent mode on this environment."

### ISSUE THREAD

**Issue by izaid** [nemequ/icc-travis#6]
I'd love to get Intel MKL installed on a Travis CI setup, but I'm getting the above error. I've done everything correct to my knowledge, including getting an INTEL_SERIAL_NUMBER.

A link to our failed CI test is at https://travis-ci.org/libdynd/libdynd/jobs/125145716.

What am I missing here? It seems we can download the installer using the script, but no more after that.

**Comment by nemequ** [comment]
It looks like that build is for a PR.  Secure environment variables aren't available in PRs because it would be easy to open a PR which reveals your secret.

**Comment by izaid** [comment]
Ah, that's a great point. Is there any way to work around this? I'd like to test a MKL-dependent library in a PR.

**Comment by nemequ** [comment]
I don't think so.  [Sometimes a trial license works](https://github.com/nemequ/icc-travis/issues/3#issuecomment-168813379), but I'm not sure what the conditions are…  I think the best you can do is to merge the PR into a staging branch to check it, then merge into master if it works.  To avoid failing PRs you can check the [`TRAVIS_PULL_REQUEST`](https://docs.travis-ci.com/user/environment-variables/#Convenience-Variables) environment variable.

**Comment by izaid** [comment]
Thanks! I gave up on the PR, and am trying it on master. What I found now is that the community edition license doesn't work -- in particular, I got a "Community Licensing for Intel® Performance Libraries" today. And Travis CI just said "The serial number you provided is not valid for this product."

**Comment by nemequ** [comment]
That doesn't sound right... I use a community edition license for Squash, though I don't use MKL.  You should really check that the SN is right.  If you have access to a web server you might want to try to GET a URL with the SN in it and check the logs (make sure to pass the quiet flags to curl or wget so the SN doesn't show up in the logs, though...)
