### ISSUE TITLE
Minimal installation (icc,openmp) states missing libintelremotemon.so

### ISSUE THREAD

**Issue by willkill07** [nemequ/icc-travis#7]
Issuing a find `$INSTALL_DIR` shows that `libintelremotemon.so` was not installed; however, the mic version was installed to `$INSTALL_DIR`/compilers_and_libraries_2016.0.109/linux/bin/intel64_mic/libintelremotemon.so

Installation command:

`${PWD}/.travis/install-${VERSION}.sh --dest $COMPILER --components icc,openmp --url $INTEL_DOWNLOAD`

VERSION corresponds to a renamed icc-travis script, COMPILER is the install location, and I added a url switch to not have it be hardcoded, though this isn't actually necessary

Here is a direct link to a travis build: https://travis-ci.org/willkill07/PolyBench-RAJA/jobs/141488457

Below is a dump of linux/bin
```
/home/travis/pkg/intel-16/compilers_and_libraries_2016.0.109/linux/bin
/home/travis/pkg/intel-16/compilers_and_libraries_2016.0.109/linux/bin/compilervars_arch.sh
/home/travis/pkg/intel-16/compilers_and_libraries_2016.0.109/linux/bin/iccvars.sh
/home/travis/pkg/intel-16/compilers_and_libraries_2016.0.109/linux/bin/compilervars_global.csh
/home/travis/pkg/intel-16/compilers_and_libraries_2016.0.109/linux/bin/compilervars.csh
/home/travis/pkg/intel-16/compilers_and_libraries_2016.0.109/linux/bin/compilervars_global.sh
/home/travis/pkg/intel-16/compilers_and_libraries_2016.0.109/linux/bin/compilervars.sh
/home/travis/pkg/intel-16/compilers_and_libraries_2016.0.109/linux/bin/iccvars.csh
/home/travis/pkg/intel-16/compilers_and_libraries_2016.0.109/linux/bin/intel64
/home/travis/pkg/intel-16/compilers_and_libraries_2016.0.109/linux/bin/intel64/icpc
/home/travis/pkg/intel-16/compilers_and_libraries_2016.0.109/linux/bin/intel64/mcpcom
/home/travis/pkg/intel-16/compilers_and_libraries_2016.0.109/linux/bin/intel64/offload_extract
/home/travis/pkg/intel-16/compilers_and_libraries_2016.0.109/linux/bin/intel64/icpc.cfg
/home/travis/pkg/intel-16/compilers_and_libraries_2016.0.109/linux/bin/intel64/icc
/home/travis/pkg/intel-16/compilers_and_libraries_2016.0.109/linux/bin/intel64/icpc_libFNP.so
/home/travis/pkg/intel-16/compilers_and_libraries_2016.0.109/linux/bin/intel64/icc.cfg
/home/travis/pkg/intel-16/compilers_and_libraries_2016.0.109/linux/bin/intel64/icc_libFNP.so
/home/travis/pkg/intel-16/compilers_and_libraries_2016.0.109/linux/bin/intel64/gfx_sys_check
/home/travis/pkg/intel-16/compilers_and_libraries_2016.0.109/linux/bin/intel64/x86_64-linux.env
/home/travis/pkg/intel-16/compilers_and_libraries_2016.0.109/linux/bin/intel64_mic
/home/travis/pkg/intel-16/compilers_and_libraries_2016.0.109/linux/bin/intel64_mic/icpc
/home/travis/pkg/intel-16/compilers_and_libraries_2016.0.109/linux/bin/intel64_mic/mcpcom
/home/travis/pkg/intel-16/compilers_and_libraries_2016.0.109/linux/bin/intel64_mic/dbmerge
/home/travis/pkg/intel-16/compilers_and_libraries_2016.0.109/linux/bin/intel64_mic/map_opts
/home/travis/pkg/intel-16/compilers_and_libraries_2016.0.109/linux/bin/intel64_mic/profmerge
/home/travis/pkg/intel-16/compilers_and_libraries_2016.0.109/linux/bin/intel64_mic/icpc.cfg
/home/travis/pkg/intel-16/compilers_and_libraries_2016.0.109/linux/bin/intel64_mic/libintelremotemon.so
/home/travis/pkg/intel-16/compilers_and_libraries_2016.0.109/linux/bin/intel64_mic/xiar
/home/travis/pkg/intel-16/compilers_and_libraries_2016.0.109/linux/bin/intel64_mic/xild
/home/travis/pkg/intel-16/compilers_and_libraries_2016.0.109/linux/bin/intel64_mic/xiar.cfg
/home/travis/pkg/intel-16/compilers_and_libraries_2016.0.109/linux/bin/intel64_mic/icc
/home/travis/pkg/intel-16/compilers_and_libraries_2016.0.109/linux/bin/intel64_mic/codecov
/home/travis/pkg/intel-16/compilers_and_libraries_2016.0.109/linux/bin/intel64_mic/icc.cfg
/home/travis/pkg/intel-16/compilers_and_libraries_2016.0.109/linux/bin/intel64_mic/proforder
/home/travis/pkg/intel-16/compilers_and_libraries_2016.0.109/linux/bin/intel64_mic/tselect
/home/travis/pkg/intel-16/compilers_and_libraries_2016.0.109/linux/bin/intel64_mic/x86_64-linux.env
/home/travis/pkg/intel-16/compilers_and_libraries_2016.0.109/linux/bin/intel64_mic/xild.cfg
/home/travis/pkg/intel-16/compilers_and_libraries_2016.0.109/linux/bin/intel64_mic/profdcg
/home/travis/pkg/intel-16/compilers_and_libraries_2016.0.109/linux/bin/intel64_gfx
/home/travis/pkg/intel-16/compilers_and_libraries_2016.0.109/linux/bin/intel64_gfx/mcpcom
/home/travis/pkg/intel-16/compilers_and_libraries_2016.0.109/linux/bin/intel64_gfx/igfxcmjit64_31.so
/home/travis/pkg/intel-16/compilers_and_libraries_2016.0.109/linux/bin/intel64_gfx/igfxcmjit64.so
/home/travis/pkg/intel-16/compilers_and_libraries_2016.0.109/linux/bin/intel64_gfx/gfx_linker
/home/travis/pkg/intel-16/compilers_and_libraries_2016.0.109/linux/bin/compilervars_arch.csh
```

**Comment by nemequ** [comment]
Sounds like you forgot to [source ~/.bashrc](https://github.com/nemequ/icc-travis#sourcing-bashrc).  See https://github.com/quixdb/squash/blob/master/.travis.yml#L93 for an example.

**Comment by willkill07** [comment]
I exported LD_LIBRARY_PATH to be what would have been written to .bashrc to
then later be sourced. The file it complains about just outright does not
exist on the file system.

*- Will*

*This email was sent from a mobile device. Please excuse brevity and typos.*

**Comment by nemequ** [comment]
That's not all there is to it; you also need to source compilervars.sh (with intel64 as an argument).

**Comment by willkill07** [comment]
Which I also do.

https://github.com/willkill07/PolyBench-RAJA/blob/master/.travis/config-intel-16.sh

Again, the so file is MISSING from the file system.

*- Will*

*This email was sent from a mobile device. Please excuse brevity and typos.*

**Comment by nemequ** [comment]
> Again, the so file is MISSING from the file system.

If that's really the issue, then it sounds like a problem with Intel's intaller.  That said, I'm not convinced; the error about not being able to find `libintelremotemon.so ` is the error that appears when the environment is not set up properly, which seems likely here, especially since some of your modifications are in exactly this area.

Just running `env` will expose your serial number, but try printing out `$LD_LIBRARY_DIRS` and make sure it is what you expect.  I can already guess that it won't be; you have a backsash before `$LD_LIBRARY_FLAGS` so you'll probably end up with something like `/home/travis/project/.travis:intel-16/ism/bin/intel64:intel-16/lib/intel64_lin:$LD_LIBRARY_PATH`.  Also note that the path names for the ICC stuff are relative, which could *definitely* be the problem… I don't even know how LD_LIBRARY_PATH handles relative paths, but that's certainly a good place to start.

There isn't really much I can do for you here.  My license for ICC is only for developing [Squash](https://quixdb.github.io/squash/); debugging your project is definitely outside that scope.  And I can't use a PR to use your license key because PRs don't have access to secure variables.

**Comment by willkill07** [comment]
Issue was with the escaped $ in the string. the file was stored elsewhere, but I pulled it from a machine to exist in the cache.

**Comment by nemequ** [comment]
FWIW, it should run unmodified in container-based build environments now.  It used to work, but apparently Travis made some changes to .bashrc.
